# Generated by Django 2.1.dev20180403030529 on 2018-04-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixGroups', '0002_auto_20180405_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
