# Generated by Django 2.1.dev20180403030529 on 2018-04-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixGroups', '0003_auto_20180405_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_number',
        ),
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.CharField(default=1, help_text='Unique Group Identifier', max_length=200),
            preserve_default=False,
        ),
    ]
