# Generated by Django 2.1.dev20180403030529 on 2018-04-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixGroups', '0005_group_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_id',
        ),
    ]
