# Generated by Django 2.1.dev20180403030529 on 2018-04-06 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mixGroups', '0006_remove_group_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Unique Group Identifier', max_length=200),
            preserve_default=False,
        ),
    ]
