# Generated by Django 2.1.dev20180403030529 on 2018-04-06 17:32

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('mixGroups', '0007_group_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='group',
            name='employee_list',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
