# Generated by Django 2.1.dev20180403030529 on 2018-04-06 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mixGroups', '0008_auto_20180406_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('runtime_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runtime', models.DateTimeField(verbose_name='date created')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
        migrations.AddField(
            model_name='group',
            name='runtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mixGroups.History'),
        ),
    ]
