# Generated by Django 2.1.dev20180403030529 on 2018-04-06 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mixGroups', '0010_auto_20180406_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='id',
        ),
        migrations.AddField(
            model_name='history',
            name='runtime_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
