# Generated by Django 2.1.dev20180403030529 on 2018-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixGroups', '0011_auto_20180406_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='runtime_id',
        ),
        migrations.AddField(
            model_name='history',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
