# Generated by Django 2.1.dev20180403030529 on 2018-04-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixGroups', '0012_auto_20180406_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='runtime',
        ),
    ]
