# Generated by Django 2.1.dev20180403030529 on 2018-04-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixGroups', '0013_remove_group_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='runtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mixGroups.History'),
        ),
    ]
